#!/bin/sh

# This script is for building deb package of serweb-frmwrk.
#
# Before running it update the debian/changelog file with running commands:
#  dch -i               # add the changelog entries in this step
#  dch -r -D stable     # change distribution from UNRELEASED to stable
#  add release label to CHANGELOG file

# stop on any error
set -e

dpkg-buildpackage -uc -us -tc -sn -A

