Document: serweb-frmwrk
Title: Debian serweb-frmwrk Manual
Author: <insert document author here>
Abstract: This manual describes what serweb-frmwrk is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/serweb-frmwrk/serweb-frmwrk.sgml.gz

Format: postscript
Files: /usr/share/doc/serweb-frmwrk/serweb-frmwrk.ps.gz

Format: text
Files: /usr/share/doc/serweb-frmwrk/serweb-frmwrk.text.gz

Format: HTML
Index: /usr/share/doc/serweb-frmwrk/html/index.html
Files: /usr/share/doc/serweb-frmwrk/html/*.html
